### ISSUE TITLE
Release on Pypi

### ISSUE THREAD

**Issue by duburcqa** [sphinx-contrib/aafig#5]
Hi !

It would be nice to release on Pypi the latest version since it adds the compatibility with Python3, now that Python2 supports has officially ended.

Best

**Comment by llucax** [comment]
Yes! I will release soon. I even got a version 1.1.0 in the pipe a long time ago, I even pushed the tag here but never did a release in pipy. I haven't used sphinx and aafig for years now (I even barely use Python these days :), so sometimes is hard not to forget about this little nice extension, sorry about that.

**Comment by llucax** [comment]
Released: https://pypi.org/project/sphinxcontrib-aafig/. This project aged quite a bit though,  for example the documentation wasn't updated because the method for uploading documentation used by this project doesn't exist anymore :shrug:. In the latest versions only bug fixes were included, so it's not a big deal for now.
